/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import domain.PartController;
import domain.Part;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author joachim
 */
public class ResourceManagementSystemFrame extends javax.swing.JFrame {

    /**
     * Creates new form ResourceManagementSystemFrame
     */
    private PartController pc = new PartController();

    public ResourceManagementSystemFrame() {
        initComponents();
    }

    private void clearGetFields() {
        jTextFieldPartNo.setText("");
        jTextFieldPartName.setText("");
        jTextFieldPartQuantity.setText("");
        jTextFieldPartDescription.setText("");
        jLabelStatus.setText("");
    }

    private void clearNewFields() {
        jTextFieldNewPartNo.setText("");
        jTextFieldNewPartName.setText("");
        jTextFieldNewPartQuantity.setText("");
        jTextFieldNewPartDescription.setText("");
        jLabelSaved.setText("");
    }

    private void clearUpdateFields() {
        jTextFieldUpdatePartNo.setText("");
        jTextFieldUpdatePartName.setText("");
        jTextFieldUpdatePartDescription.setText("");
        jLabelUpdated.setText("");
    }

    private void clearUpdateQtyFields() {
        jTextFieldUpdateQtyNo.setText("");
        jTextFieldUpdateQtyName.setText("");
        jTextFieldUpdateQtyQty.setText("");
        jLabelQty.setText("");
    }

    private void clearDeleteFields() {
        jTextFieldDeletePartNo.setText("");
        jTextFieldDeletePartName.setText("");
        jTextFieldDeletePartQuantity.setText("");
        jTextFieldDeletePartDescription.setText("");
        jLabelDeleted.setText("");
    }
    
    private void clearDeleteFields2() {
        jTextFieldDeletePartNo.setText("");
        jTextFieldDeletePartName.setText("");
        jTextFieldDeletePartQuantity.setText("");
        jTextFieldDeletePartDescription.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameNewPart = new javax.swing.JFrame();
        jPanelNewPart = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNewPartNo = new javax.swing.JTextField();
        jTextFieldNewPartName = new javax.swing.JTextField();
        jTextFieldNewPartQuantity = new javax.swing.JTextField();
        jTextFieldNewPartDescription = new javax.swing.JTextField();
        jButtonSavePart = new javax.swing.JButton();
        jButtonNewPartBack = new javax.swing.JButton();
        jLabelSaved = new javax.swing.JLabel();
        jFrameUpdatePart = new javax.swing.JFrame();
        jPanelUpdatePart = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldUpdatePartNo = new javax.swing.JTextField();
        jTextFieldUpdatePartName = new javax.swing.JTextField();
        jTextFieldUpdatePartDescription = new javax.swing.JTextField();
        jButtonUpdatePartUpdate = new javax.swing.JButton();
        jButtonUpdatePartBack = new javax.swing.JButton();
        jButtonUpdatePartLoad = new javax.swing.JButton();
        jLabelUpdateStatus = new javax.swing.JLabel();
        jLabelUpdated = new javax.swing.JLabel();
        jFrameUpdateQty = new javax.swing.JFrame();
        jPanelUpdateQty = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldUpdateQtyNo = new javax.swing.JTextField();
        jTextFieldUpdateQtyName = new javax.swing.JTextField();
        jTextFieldUpdateQtyQty = new javax.swing.JTextField();
        jButtonUpdateQtyUpdate = new javax.swing.JButton();
        jButtonUpdateQtyBack = new javax.swing.JButton();
        jButtonUpdateQtyLoad = new javax.swing.JButton();
        jLabelQty = new javax.swing.JLabel();
        jLabelUpdateQtyStatus = new javax.swing.JLabel();
        jFrameDeletePart = new javax.swing.JFrame();
        jPanelDeletePart = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldDeletePartNo = new javax.swing.JTextField();
        jTextFieldDeletePartName = new javax.swing.JTextField();
        jTextFieldDeletePartQuantity = new javax.swing.JTextField();
        jTextFieldDeletePartDescription = new javax.swing.JTextField();
        jButtonDeletePartDelete = new javax.swing.JButton();
        jButtonDeletePartBack = new javax.swing.JButton();
        jLabelDeleted = new javax.swing.JLabel();
        jButtonDeleteLoad = new javax.swing.JButton();
        jLabelDeleteStatus = new javax.swing.JLabel();
        jTabbedPaneParts = new javax.swing.JTabbedPane();
        jPanelGetPart = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPartNo = new javax.swing.JTextField();
        jTextFieldPartName = new javax.swing.JTextField();
        jTextFieldPartQuantity = new javax.swing.JTextField();
        jButtonGetPart = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();
        jButtonNewPart = new javax.swing.JButton();
        jButtonUpdatePart = new javax.swing.JButton();
        jButtonUpdateQty = new javax.swing.JButton();
        jButtonDeletePart = new javax.swing.JButton();
        jTextFieldPartDescription = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        jFrameNewPart.setMinimumSize(new java.awt.Dimension(550, 350));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Create new part");

        jLabel6.setText("Part No");

        jLabel7.setText("Part Name");

        jLabel8.setText("Part Quantity");

        jLabel9.setText("Part Description");

        jTextFieldNewPartNo.setToolTipText("Leave empty for auto-number");

        jButtonSavePart.setText("Save Part");
        jButtonSavePart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSavePartActionPerformed(evt);
            }
        });

        jButtonNewPartBack.setText("Back");
        jButtonNewPartBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewPartBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNewPartLayout = new javax.swing.GroupLayout(jPanelNewPart);
        jPanelNewPart.setLayout(jPanelNewPartLayout);
        jPanelNewPartLayout.setHorizontalGroup(
            jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewPartLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSaved)
                    .addComponent(jLabel5)
                    .addGroup(jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelNewPartLayout.createSequentialGroup()
                            .addComponent(jButtonSavePart)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                            .addComponent(jButtonNewPartBack))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelNewPartLayout.createSequentialGroup()
                            .addGroup(jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(21, 21, 21)
                            .addGroup(jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldNewPartName)
                                .addComponent(jTextFieldNewPartNo, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                .addComponent(jTextFieldNewPartQuantity)
                                .addComponent(jTextFieldNewPartDescription)))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanelNewPartLayout.setVerticalGroup(
            jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewPartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addGroup(jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldNewPartNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldNewPartName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldNewPartQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldNewPartDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSavePart)
                    .addComponent(jButtonNewPartBack))
                .addGap(18, 18, 18)
                .addComponent(jLabelSaved)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrameNewPartLayout = new javax.swing.GroupLayout(jFrameNewPart.getContentPane());
        jFrameNewPart.getContentPane().setLayout(jFrameNewPartLayout);
        jFrameNewPartLayout.setHorizontalGroup(
            jFrameNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNewPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrameNewPartLayout.setVerticalGroup(
            jFrameNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNewPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFrameUpdatePart.setMinimumSize(new java.awt.Dimension(550, 350));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Update part");

        jLabel11.setText("Part No");

        jLabel12.setText("Part Name");

        jLabel14.setText("Part Description");

        jTextFieldUpdatePartNo.setToolTipText("Leave empty for auto-number");

        jButtonUpdatePartUpdate.setText("Update Part");
        jButtonUpdatePartUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdatePartUpdateActionPerformed(evt);
            }
        });

        jButtonUpdatePartBack.setText("Back");
        jButtonUpdatePartBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdatePartBackActionPerformed(evt);
            }
        });

        jButtonUpdatePartLoad.setText("Load part");
        jButtonUpdatePartLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdatePartLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUpdatePartLayout = new javax.swing.GroupLayout(jPanelUpdatePart);
        jPanelUpdatePart.setLayout(jPanelUpdatePartLayout);
        jPanelUpdatePartLayout.setHorizontalGroup(
            jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpdatePartLayout.createSequentialGroup()
                .addGroup(jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUpdatePartLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel10))
                    .addGroup(jPanelUpdatePartLayout.createSequentialGroup()
                        .addGroup(jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUpdatePartLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabelUpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpdatePartLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelUpdated)
                                    .addComponent(jButtonUpdatePartLoad))
                                .addGap(32, 32, 32)))
                        .addGroup(jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelUpdatePartLayout.createSequentialGroup()
                                .addComponent(jButtonUpdatePartUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(jButtonUpdatePartBack))
                            .addComponent(jTextFieldUpdatePartName)
                            .addComponent(jTextFieldUpdatePartNo)
                            .addComponent(jTextFieldUpdatePartDescription))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanelUpdatePartLayout.setVerticalGroup(
            jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpdatePartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(9, 9, 9)
                .addComponent(jLabelUpdateStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldUpdatePartNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldUpdatePartName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldUpdatePartDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdatePartLoad)
                    .addComponent(jButtonUpdatePartUpdate)
                    .addComponent(jButtonUpdatePartBack))
                .addGap(18, 18, 18)
                .addComponent(jLabelUpdated)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrameUpdatePartLayout = new javax.swing.GroupLayout(jFrameUpdatePart.getContentPane());
        jFrameUpdatePart.getContentPane().setLayout(jFrameUpdatePartLayout);
        jFrameUpdatePartLayout.setHorizontalGroup(
            jFrameUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelUpdatePart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jFrameUpdatePartLayout.setVerticalGroup(
            jFrameUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelUpdatePart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jFrameUpdateQty.setMinimumSize(new java.awt.Dimension(550, 350));

        jPanelUpdateQty.setMinimumSize(new java.awt.Dimension(410, 225));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Update quantity");

        jLabel15.setText("Part No");

        jLabel16.setText("Part Name");

        jLabel17.setText("Part Quantity");

        jTextFieldUpdateQtyNo.setToolTipText("Leave empty for auto-number");

        jButtonUpdateQtyUpdate.setText("Update Qty");
        jButtonUpdateQtyUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateQtyUpdateActionPerformed(evt);
            }
        });

        jButtonUpdateQtyBack.setText("Back");
        jButtonUpdateQtyBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateQtyBackActionPerformed(evt);
            }
        });

        jButtonUpdateQtyLoad.setText("Load part");
        jButtonUpdateQtyLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateQtyLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUpdateQtyLayout = new javax.swing.GroupLayout(jPanelUpdateQty);
        jPanelUpdateQty.setLayout(jPanelUpdateQtyLayout);
        jPanelUpdateQtyLayout.setHorizontalGroup(
            jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpdateQtyLayout.createSequentialGroup()
                .addGroup(jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUpdateQtyLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel13))
                    .addGroup(jPanelUpdateQtyLayout.createSequentialGroup()
                        .addGroup(jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUpdateQtyLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabelUpdateQtyStatus))
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpdateQtyLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonUpdateQtyLoad)
                                    .addComponent(jLabelQty))
                                .addGap(32, 32, 32)))
                        .addGroup(jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelUpdateQtyLayout.createSequentialGroup()
                                .addComponent(jButtonUpdateQtyUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(jButtonUpdateQtyBack))
                            .addComponent(jTextFieldUpdateQtyName)
                            .addComponent(jTextFieldUpdateQtyNo)
                            .addComponent(jTextFieldUpdateQtyQty))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanelUpdateQtyLayout.setVerticalGroup(
            jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpdateQtyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUpdateQtyStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldUpdateQtyNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldUpdateQtyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldUpdateQtyQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdateQtyLoad)
                    .addComponent(jButtonUpdateQtyUpdate)
                    .addComponent(jButtonUpdateQtyBack))
                .addGap(24, 24, 24)
                .addComponent(jLabelQty)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrameUpdateQtyLayout = new javax.swing.GroupLayout(jFrameUpdateQty.getContentPane());
        jFrameUpdateQty.getContentPane().setLayout(jFrameUpdateQtyLayout);
        jFrameUpdateQtyLayout.setHorizontalGroup(
            jFrameUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelUpdateQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrameUpdateQtyLayout.setVerticalGroup(
            jFrameUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelUpdateQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFrameDeletePart.setMinimumSize(new java.awt.Dimension(550, 350));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Delete part");

        jLabel19.setText("Part No");

        jLabel20.setText("Part Name");

        jLabel21.setText("Part Quantity");

        jLabel22.setText("Part Description");

        jTextFieldDeletePartNo.setToolTipText("Leave empty for auto-number");

        jButtonDeletePartDelete.setText("Delete Part");
        jButtonDeletePartDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletePartDeleteActionPerformed(evt);
            }
        });

        jButtonDeletePartBack.setText("Back");
        jButtonDeletePartBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletePartBackActionPerformed(evt);
            }
        });

        jButtonDeleteLoad.setText("Load");
        jButtonDeleteLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDeletePartLayout = new javax.swing.GroupLayout(jPanelDeletePart);
        jPanelDeletePart.setLayout(jPanelDeletePartLayout);
        jPanelDeletePartLayout.setHorizontalGroup(
            jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeletePartLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDeleteStatus)
                    .addGroup(jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelDeletePartLayout.createSequentialGroup()
                            .addComponent(jButtonDeleteLoad)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonDeletePartDelete)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                            .addComponent(jButtonDeletePartBack))
                        .addGroup(jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDeleted)
                            .addComponent(jLabel18)
                            .addGroup(jPanelDeletePartLayout.createSequentialGroup()
                                .addGroup(jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22))
                                .addGap(21, 21, 21)
                                .addGroup(jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldDeletePartName)
                                    .addComponent(jTextFieldDeletePartNo, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDeletePartQuantity)
                                    .addComponent(jTextFieldDeletePartDescription))))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanelDeletePartLayout.setVerticalGroup(
            jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeletePartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(9, 9, 9)
                .addComponent(jLabelDeleteStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldDeletePartNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldDeletePartName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextFieldDeletePartQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldDeletePartDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDeletePartDelete)
                    .addComponent(jButtonDeletePartBack)
                    .addComponent(jButtonDeleteLoad))
                .addGap(18, 18, 18)
                .addComponent(jLabelDeleted)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrameDeletePartLayout = new javax.swing.GroupLayout(jFrameDeletePart.getContentPane());
        jFrameDeletePart.getContentPane().setLayout(jFrameDeletePartLayout);
        jFrameDeletePartLayout.setHorizontalGroup(
            jFrameDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDeletePart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrameDeletePartLayout.setVerticalGroup(
            jFrameDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDeletePart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPaneParts.setMinimumSize(new java.awt.Dimension(550, 350));

        jLabel1.setText("Part No");

        jLabel2.setText("Part Name");

        jLabel3.setText("Quantity");

        jLabel4.setText("Part Description");

        jButtonGetPart.setText("Get Part");
        jButtonGetPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetPartActionPerformed(evt);
            }
        });

        jButtonNewPart.setText("New Part");
        jButtonNewPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewPartActionPerformed(evt);
            }
        });

        jButtonUpdatePart.setText("Update Part");
        jButtonUpdatePart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdatePartActionPerformed(evt);
            }
        });

        jButtonUpdateQty.setText("Update Qty");
        jButtonUpdateQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateQtyActionPerformed(evt);
            }
        });

        jButtonDeletePart.setText("Delete Part");
        jButtonDeletePart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletePartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGetPartLayout = new javax.swing.GroupLayout(jPanelGetPart);
        jPanelGetPart.setLayout(jPanelGetPartLayout);
        jPanelGetPartLayout.setHorizontalGroup(
            jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGetPartLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGetPartLayout.createSequentialGroup()
                        .addGroup(jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelGetPartLayout.createSequentialGroup()
                                .addGroup(jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(28, 28, 28)
                                .addGroup(jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldPartNo)
                                    .addComponent(jTextFieldPartName)
                                    .addComponent(jTextFieldPartQuantity)
                                    .addComponent(jTextFieldPartDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                            .addComponent(jButtonGetPart, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonUpdatePart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonNewPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonUpdateQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDeletePart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanelGetPartLayout.setVerticalGroup(
            jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGetPartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPartNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewPart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPartName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdatePart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPartQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdateQty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldPartDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeletePart))
                .addGap(18, 18, 18)
                .addComponent(jButtonGetPart)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPaneParts.addTab("Parts", jPanelGetPart);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jTabbedPaneParts.addTab("tab2", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneParts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneParts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGetPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetPartActionPerformed
        // TODO add your handling code here:
        int pno = 0;

        if (jTextFieldPartNo.getText().equals("")) {
            pno = 0;
        } else {
            pno = Integer.parseInt(jTextFieldPartNo.getText());
        }

        clearGetFields();
        Part p = pc.getPart(pno);

        if (p != null) {
            jTextFieldPartName.setText(p.getPnavn());
            jTextFieldPartNo.setText(p.getPnum() + "");
            jTextFieldPartQuantity.setText(p.getQty() + "");
            jTextFieldPartDescription.setText(p.getPbeskrivelse());
        } else {
            jLabelStatus.setText("No such part!");
        }

    }//GEN-LAST:event_jButtonGetPartActionPerformed

    private void jButtonNewPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewPartActionPerformed
        // TODO add your handling code here:
        jFrameNewPart.setVisible(true);
    }//GEN-LAST:event_jButtonNewPartActionPerformed

    private void jButtonSavePartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSavePartActionPerformed
        // TODO add your handling code here:
        String newName = jTextFieldNewPartName.getText();
        int newQty = Integer.parseInt(jTextFieldNewPartQuantity.getText());
        String newDesc = jTextFieldNewPartDescription.getText();

        if (jTextFieldNewPartNo.getText().compareTo("") == 0) {
            Part p = new Part(newName, newDesc, newQty);
            pc.saveNewPart(p);
            clearNewFields();
        } else {
            Part p = new Part(Integer.parseInt(jTextFieldNewPartNo.getText()), newName, newDesc, newQty);
            pc.saveNewPartWitnum(p);
            clearNewFields();
        }

        jLabelSaved.setText("Saved");
    }//GEN-LAST:event_jButtonSavePartActionPerformed

    private void jButtonNewPartBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewPartBackActionPerformed
        // TODO add your handling code here:
        jFrameNewPart.setVisible(false);
        jFrameNewPart.dispose();
    }//GEN-LAST:event_jButtonNewPartBackActionPerformed

    private void jButtonUpdatePartUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdatePartUpdateActionPerformed
        // TODO add your handling code here:
        String updateName = jTextFieldUpdatePartName.getText();
        String updateDescription = jTextFieldUpdatePartDescription.getText();
        int updatePno = Integer.parseInt(jTextFieldUpdatePartNo.getText());

        Part p = new Part(updatePno, updateName, updateName, 0);

        pc.updatePart(p);

        clearUpdateFields();
        jLabelUpdated.setText("Updated");
    }//GEN-LAST:event_jButtonUpdatePartUpdateActionPerformed

    private void jButtonUpdatePartBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdatePartBackActionPerformed
        // TODO add your handling code here:
        jFrameUpdatePart.setVisible(false);
        jFrameUpdatePart.dispose();
    }//GEN-LAST:event_jButtonUpdatePartBackActionPerformed

    private void jButtonUpdatePartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdatePartActionPerformed
        // TODO add your handling code here:
        jFrameUpdatePart.setVisible(true);
    }//GEN-LAST:event_jButtonUpdatePartActionPerformed

    private void jButtonUpdatePartLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdatePartLoadActionPerformed
        // TODO add your handling code here:
        int pno = 0;

        if (jTextFieldUpdatePartNo.getText().equals("")) {
            pno = 0;
        } else {
            pno = Integer.parseInt(jTextFieldUpdatePartNo.getText());
        }

        Part p = pc.getPart(pno);

        if (p != null) {
            jTextFieldUpdatePartName.setText(p.getPnavn());
            jTextFieldUpdatePartNo.setText(p.getPnum() + "");
            jTextFieldUpdatePartDescription.setText(p.getPbeskrivelse());
        } else {
            jLabelUpdateStatus.setText("No such part!");
        }
    }//GEN-LAST:event_jButtonUpdatePartLoadActionPerformed

    private void jButtonUpdateQtyUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateQtyUpdateActionPerformed
        // TODO add your handling code here:
        int pnum, qty;

        if (jTextFieldDeletePartNo.getText().equals("")) {
            pnum = 0;
        } else {
            pnum = Integer.parseInt(jTextFieldUpdateQtyNo.getText());
        }

        if (jTextFieldDeletePartNo.getText().equals("")) {
            qty = 0;
        } else {
            qty = Integer.parseInt(jTextFieldUpdateQtyQty.getText());
        }

        pc.updatePartQty(pnum, qty);

        clearUpdateQtyFields();
        jLabelQty.setText("Updated");
    }//GEN-LAST:event_jButtonUpdateQtyUpdateActionPerformed

    private void jButtonUpdateQtyBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateQtyBackActionPerformed
        // TODO add your handling code here:
        jFrameUpdateQty.setVisible(false);
        jFrameUpdateQty.dispose();
    }//GEN-LAST:event_jButtonUpdateQtyBackActionPerformed

    private void jButtonUpdateQtyLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateQtyLoadActionPerformed
        // TODO add your handling code here:
        int pno = 0;

        if (jTextFieldUpdateQtyNo.getText().equals("")) {
            pno = 0;
        } else {
            pno = Integer.parseInt(jTextFieldUpdateQtyNo.getText());
        }

        clearDeleteFields();

        Part p = pc.getPart(pno);

        if (p != null) {
            jTextFieldUpdateQtyName.setText(p.getPnavn());
            jTextFieldUpdateQtyNo.setText(p.getPnum() + "");
            jTextFieldUpdateQtyQty.setText(p.getQty() + "");
        } else {
            jLabelUpdateQtyStatus.setText("No such part!");
        }
    }//GEN-LAST:event_jButtonUpdateQtyLoadActionPerformed

    private void jButtonUpdateQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateQtyActionPerformed
        // TODO add your handling code here:
        jFrameUpdateQty.setVisible(true);
    }//GEN-LAST:event_jButtonUpdateQtyActionPerformed

    private void jButtonDeletePartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletePartActionPerformed
        // TODO add your handling code here:
        jFrameDeletePart.setVisible(true);
    }//GEN-LAST:event_jButtonDeletePartActionPerformed

    private void jButtonDeletePartDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletePartDeleteActionPerformed
        // TODO add your handling code here:
        int pno;

        if (jTextFieldDeletePartNo.getText().equals("")) {
            pno = 0;
        } else {
            pno = Integer.parseInt(jTextFieldDeletePartNo.getText());
        }

        int reply = JOptionPane.showConfirmDialog(null, "Deleting cannot be undone. Are you sure you want to delete this part?",
                "Warning", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            pc.deletePart(pno);
        }

        clearDeleteFields2();
        jLabelDeleted.setText("Deleted");
    }//GEN-LAST:event_jButtonDeletePartDeleteActionPerformed

    private void jButtonDeletePartBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletePartBackActionPerformed
        // TODO add your handling code here:
        jFrameDeletePart.setVisible(false);
        jFrameDeletePart.dispose();
    }//GEN-LAST:event_jButtonDeletePartBackActionPerformed

    private void jButtonDeleteLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteLoadActionPerformed
        // TODO add your handling code here:
        int pno = 0;

        if (jTextFieldDeletePartNo.getText().equals("")) {
            pno = 0;
        } else {
            pno = Integer.parseInt(jTextFieldDeletePartNo.getText());
        }

        clearUpdateQtyFields();

        Part p = pc.getPart(pno);

        if (p != null) {
            jTextFieldDeletePartName.setText(p.getPnavn());
            jTextFieldDeletePartNo.setText(p.getPnum() + "");
            jTextFieldDeletePartQuantity.setText(p.getQty() + "");
            jTextFieldDeletePartDescription.setText(p.getPbeskrivelse());
        } else {
            jLabelDeleteStatus.setText("No such part!");
        }
    }//GEN-LAST:event_jButtonDeleteLoadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResourceManagementSystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResourceManagementSystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResourceManagementSystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResourceManagementSystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResourceManagementSystemFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteLoad;
    private javax.swing.JButton jButtonDeletePart;
    private javax.swing.JButton jButtonDeletePartBack;
    private javax.swing.JButton jButtonDeletePartDelete;
    private javax.swing.JButton jButtonGetPart;
    private javax.swing.JButton jButtonNewPart;
    private javax.swing.JButton jButtonNewPartBack;
    private javax.swing.JButton jButtonSavePart;
    private javax.swing.JButton jButtonUpdatePart;
    private javax.swing.JButton jButtonUpdatePartBack;
    private javax.swing.JButton jButtonUpdatePartLoad;
    private javax.swing.JButton jButtonUpdatePartUpdate;
    private javax.swing.JButton jButtonUpdateQty;
    private javax.swing.JButton jButtonUpdateQtyBack;
    private javax.swing.JButton jButtonUpdateQtyLoad;
    private javax.swing.JButton jButtonUpdateQtyUpdate;
    private javax.swing.JFrame jFrameDeletePart;
    private javax.swing.JFrame jFrameNewPart;
    private javax.swing.JFrame jFrameUpdatePart;
    private javax.swing.JFrame jFrameUpdateQty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDeleteStatus;
    private javax.swing.JLabel jLabelDeleted;
    private javax.swing.JLabel jLabelQty;
    private javax.swing.JLabel jLabelSaved;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelUpdateQtyStatus;
    private javax.swing.JLabel jLabelUpdateStatus;
    private javax.swing.JLabel jLabelUpdated;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDeletePart;
    private javax.swing.JPanel jPanelGetPart;
    private javax.swing.JPanel jPanelNewPart;
    private javax.swing.JPanel jPanelUpdatePart;
    private javax.swing.JPanel jPanelUpdateQty;
    private javax.swing.JTabbedPane jTabbedPaneParts;
    private javax.swing.JTextField jTextFieldDeletePartDescription;
    private javax.swing.JTextField jTextFieldDeletePartName;
    private javax.swing.JTextField jTextFieldDeletePartNo;
    private javax.swing.JTextField jTextFieldDeletePartQuantity;
    private javax.swing.JTextField jTextFieldNewPartDescription;
    private javax.swing.JTextField jTextFieldNewPartName;
    private javax.swing.JTextField jTextFieldNewPartNo;
    private javax.swing.JTextField jTextFieldNewPartQuantity;
    private javax.swing.JTextField jTextFieldPartDescription;
    private javax.swing.JTextField jTextFieldPartName;
    private javax.swing.JTextField jTextFieldPartNo;
    private javax.swing.JTextField jTextFieldPartQuantity;
    private javax.swing.JTextField jTextFieldUpdatePartDescription;
    private javax.swing.JTextField jTextFieldUpdatePartName;
    private javax.swing.JTextField jTextFieldUpdatePartNo;
    private javax.swing.JTextField jTextFieldUpdateQtyName;
    private javax.swing.JTextField jTextFieldUpdateQtyNo;
    private javax.swing.JTextField jTextFieldUpdateQtyQty;
    // End of variables declaration//GEN-END:variables
}
