/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import domain.PartController;
import domain.Part;
import domain.Vogn;
import domain.VognController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author joachim
 */
public class ResourceManagementSystemFrame extends javax.swing.JFrame {

    /**
     * Creates new form ResourceManagementSystemFrame
     */
    private final PartController pc = new PartController();
    private final VognController vc = new VognController();

    public ResourceManagementSystemFrame() {
        initComponents();
    }

    private void clearGetFields() {
        jTextFieldPartNo.setText("");
        jTextFieldPartName.setText("");
        jTextFieldPartQuantity.setText("");
        jTextFieldPartDescription.setText("");
        jLabelStatus.setText("");
    }

    private void clearNewFields() {
        jTextFieldNewPartNo.setText("");
        jTextFieldNewPartName.setText("");
        jTextFieldNewPartQuantity.setText("");
        jTextFieldNewPartDescription.setText("");
        jLabelSaved.setText("");
    }

    private void clearUpdateFields() {
        jTextFieldUpdatePartNo.setText("");
        jTextFieldUpdatePartName.setText("");
        jTextFieldUpdatePartDescription.setText("");
        jLabelUpdated.setText("");
    }

    private void clearUpdateQtyFields() {
        jTextFieldUpdateQtyNo.setText("");
        jTextFieldUpdateQtyName.setText("");
        jTextFieldUpdateQtyQty.setText("");
        jLabelQty.setText("");
    }

    private void clearDeleteFields() {
        jTextFieldDeletePartNo.setText("");
        jTextFieldDeletePartName.setText("");
        jTextFieldDeletePartQuantity.setText("");
        jTextFieldDeletePartDescription.setText("");
        jLabelDeleted.setText("");
    }

    private void clearDeleteFields2() {
        jTextFieldDeletePartNo.setText("");
        jTextFieldDeletePartName.setText("");
        jTextFieldDeletePartQuantity.setText("");
        jTextFieldDeletePartDescription.setText("");
    }

    private void clearVognFields() {
        jTextFieldVognNo.setText("");
        jTextFieldVognOno.setText("");
        jTextFieldVognType.setText("");
        jTextFieldVognStatus.setText("");
        jTextFieldVognReservedFrom.setText("");
        jTextFieldVognReservedTo.setText("");
        jLabelVognStatus.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameNewPart = new javax.swing.JFrame();
        jPanelNewPart = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNewPartNo = new javax.swing.JTextField();
        jTextFieldNewPartName = new javax.swing.JTextField();
        jTextFieldNewPartQuantity = new javax.swing.JTextField();
        jTextFieldNewPartDescription = new javax.swing.JTextField();
        jButtonSavePart = new javax.swing.JButton();
        jButtonNewPartBack = new javax.swing.JButton();
        jLabelSaved = new javax.swing.JLabel();
        jFrameUpdatePart = new javax.swing.JFrame();
        jPanelUpdatePart = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldUpdatePartNo = new javax.swing.JTextField();
        jTextFieldUpdatePartName = new javax.swing.JTextField();
        jTextFieldUpdatePartDescription = new javax.swing.JTextField();
        jButtonUpdatePartUpdate = new javax.swing.JButton();
        jButtonUpdatePartBack = new javax.swing.JButton();
        jButtonUpdatePartLoad = new javax.swing.JButton();
        jLabelUpdateStatus = new javax.swing.JLabel();
        jLabelUpdated = new javax.swing.JLabel();
        jFrameUpdateQty = new javax.swing.JFrame();
        jPanelUpdateQty = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldUpdateQtyNo = new javax.swing.JTextField();
        jTextFieldUpdateQtyName = new javax.swing.JTextField();
        jTextFieldUpdateQtyQty = new javax.swing.JTextField();
        jButtonUpdateQtyUpdate = new javax.swing.JButton();
        jButtonUpdateQtyBack = new javax.swing.JButton();
        jButtonUpdateQtyLoad = new javax.swing.JButton();
        jLabelQty = new javax.swing.JLabel();
        jLabelUpdateQtyStatus = new javax.swing.JLabel();
        jFrameDeletePart = new javax.swing.JFrame();
        jPanelDeletePart = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldDeletePartNo = new javax.swing.JTextField();
        jTextFieldDeletePartName = new javax.swing.JTextField();
        jTextFieldDeletePartQuantity = new javax.swing.JTextField();
        jTextFieldDeletePartDescription = new javax.swing.JTextField();
        jButtonDeletePartDelete = new javax.swing.JButton();
        jButtonDeletePartBack = new javax.swing.JButton();
        jLabelDeleted = new javax.swing.JLabel();
        jButtonDeleteLoad = new javax.swing.JButton();
        jLabelDeleteStatus = new javax.swing.JLabel();
        jFrameAllParts = new javax.swing.JFrame();
        jPanelAllParts = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAllPartsLoad = new javax.swing.JButton();
        jButtonAllPartsBack = new javax.swing.JButton();
        jFrameNewVogn = new javax.swing.JFrame();
        jPanelNewPart1 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextFieldVognNewNo = new javax.swing.JTextField();
        jTextFieldVognNewType = new javax.swing.JTextField();
        jTextFieldVognNewStatus = new javax.swing.JTextField();
        jTextFieldVognNewOno = new javax.swing.JTextField();
        jButtonSaveVogn = new javax.swing.JButton();
        jButtonNewVognBack = new javax.swing.JButton();
        jLabelSaved1 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextFieldVognNewResFrom = new javax.swing.JTextField();
        jTextFieldVognNewResUntil = new javax.swing.JTextField();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelGetPart = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPartNo = new javax.swing.JTextField();
        jTextFieldPartName = new javax.swing.JTextField();
        jTextFieldPartQuantity = new javax.swing.JTextField();
        jButtonGetPart = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();
        jButtonNewPart = new javax.swing.JButton();
        jButtonUpdatePart = new javax.swing.JButton();
        jButtonUpdateQty = new javax.swing.JButton();
        jButtonDeletePart = new javax.swing.JButton();
        jTextFieldPartDescription = new javax.swing.JTextField();
        jButtonClear = new javax.swing.JButton();
        jButtonAllParts = new javax.swing.JButton();
        jPanelGetVogn = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldVognNo = new javax.swing.JTextField();
        jTextFieldVognType = new javax.swing.JTextField();
        jTextFieldVognStatus = new javax.swing.JTextField();
        jButtonGetVogn = new javax.swing.JButton();
        jLabelVognStatus = new javax.swing.JLabel();
        jButtonNewVogn = new javax.swing.JButton();
        jButtonUpdateVogn = new javax.swing.JButton();
        jButtonDeleteVogn = new javax.swing.JButton();
        jTextFieldVognOno = new javax.swing.JTextField();
        jButtonVognClear = new javax.swing.JButton();
        jButtonAllVogn = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldVognReservedFrom = new javax.swing.JTextField();
        jTextFieldVognReservedTo = new javax.swing.JTextField();

        jFrameNewPart.setMinimumSize(new java.awt.Dimension(550, 350));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Create new part");

        jLabel6.setText("Part No");

        jLabel7.setText("Part Name");

        jLabel8.setText("Part Quantity");

        jLabel9.setText("Part Description");

        jTextFieldNewPartNo.setToolTipText("Leave empty for auto-number");
        jTextFieldNewPartNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNewPartNoFocusGained(evt);
            }
        });

        jButtonSavePart.setText("Save Part");
        jButtonSavePart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSavePartActionPerformed(evt);
            }
        });

        jButtonNewPartBack.setText("Back");
        jButtonNewPartBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewPartBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNewPartLayout = new javax.swing.GroupLayout(jPanelNewPart);
        jPanelNewPart.setLayout(jPanelNewPartLayout);
        jPanelNewPartLayout.setHorizontalGroup(
            jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewPartLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSaved)
                    .addComponent(jLabel5)
                    .addGroup(jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelNewPartLayout.createSequentialGroup()
                            .addComponent(jButtonSavePart)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                            .addComponent(jButtonNewPartBack))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelNewPartLayout.createSequentialGroup()
                            .addGroup(jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(21, 21, 21)
                            .addGroup(jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldNewPartName)
                                .addComponent(jTextFieldNewPartNo, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                .addComponent(jTextFieldNewPartQuantity)
                                .addComponent(jTextFieldNewPartDescription)))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanelNewPartLayout.setVerticalGroup(
            jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewPartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addGroup(jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldNewPartNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldNewPartName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldNewPartQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldNewPartDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSavePart)
                    .addComponent(jButtonNewPartBack))
                .addGap(18, 18, 18)
                .addComponent(jLabelSaved)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrameNewPartLayout = new javax.swing.GroupLayout(jFrameNewPart.getContentPane());
        jFrameNewPart.getContentPane().setLayout(jFrameNewPartLayout);
        jFrameNewPartLayout.setHorizontalGroup(
            jFrameNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNewPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrameNewPartLayout.setVerticalGroup(
            jFrameNewPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNewPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFrameUpdatePart.setMinimumSize(new java.awt.Dimension(550, 350));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Update part");

        jLabel11.setText("Part No");

        jLabel12.setText("Part Name");

        jLabel14.setText("Part Description");

        jTextFieldUpdatePartNo.setToolTipText("Leave empty for auto-number");
        jTextFieldUpdatePartNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUpdatePartNoFocusGained(evt);
            }
        });

        jButtonUpdatePartUpdate.setText("Update Part");
        jButtonUpdatePartUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdatePartUpdateActionPerformed(evt);
            }
        });

        jButtonUpdatePartBack.setText("Back");
        jButtonUpdatePartBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdatePartBackActionPerformed(evt);
            }
        });

        jButtonUpdatePartLoad.setText("Load part");
        jButtonUpdatePartLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdatePartLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUpdatePartLayout = new javax.swing.GroupLayout(jPanelUpdatePart);
        jPanelUpdatePart.setLayout(jPanelUpdatePartLayout);
        jPanelUpdatePartLayout.setHorizontalGroup(
            jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpdatePartLayout.createSequentialGroup()
                .addGroup(jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUpdatePartLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel10))
                    .addGroup(jPanelUpdatePartLayout.createSequentialGroup()
                        .addGroup(jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUpdatePartLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabelUpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpdatePartLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelUpdated)
                                    .addComponent(jButtonUpdatePartLoad))
                                .addGap(32, 32, 32)))
                        .addGroup(jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelUpdatePartLayout.createSequentialGroup()
                                .addComponent(jButtonUpdatePartUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(jButtonUpdatePartBack))
                            .addComponent(jTextFieldUpdatePartName)
                            .addComponent(jTextFieldUpdatePartNo)
                            .addComponent(jTextFieldUpdatePartDescription))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanelUpdatePartLayout.setVerticalGroup(
            jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpdatePartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(9, 9, 9)
                .addComponent(jLabelUpdateStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldUpdatePartNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldUpdatePartName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldUpdatePartDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdatePartLoad)
                    .addComponent(jButtonUpdatePartUpdate)
                    .addComponent(jButtonUpdatePartBack))
                .addGap(18, 18, 18)
                .addComponent(jLabelUpdated)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrameUpdatePartLayout = new javax.swing.GroupLayout(jFrameUpdatePart.getContentPane());
        jFrameUpdatePart.getContentPane().setLayout(jFrameUpdatePartLayout);
        jFrameUpdatePartLayout.setHorizontalGroup(
            jFrameUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelUpdatePart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jFrameUpdatePartLayout.setVerticalGroup(
            jFrameUpdatePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelUpdatePart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jFrameUpdateQty.setMinimumSize(new java.awt.Dimension(550, 350));

        jPanelUpdateQty.setMinimumSize(new java.awt.Dimension(410, 225));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Update quantity");

        jLabel15.setText("Part No");

        jLabel16.setText("Part Name");

        jLabel17.setText("Part Quantity");

        jTextFieldUpdateQtyNo.setToolTipText("Leave empty for auto-number");
        jTextFieldUpdateQtyNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUpdateQtyNoFocusGained(evt);
            }
        });

        jButtonUpdateQtyUpdate.setText("Update Qty");
        jButtonUpdateQtyUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateQtyUpdateActionPerformed(evt);
            }
        });

        jButtonUpdateQtyBack.setText("Back");
        jButtonUpdateQtyBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateQtyBackActionPerformed(evt);
            }
        });

        jButtonUpdateQtyLoad.setText("Load part");
        jButtonUpdateQtyLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateQtyLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUpdateQtyLayout = new javax.swing.GroupLayout(jPanelUpdateQty);
        jPanelUpdateQty.setLayout(jPanelUpdateQtyLayout);
        jPanelUpdateQtyLayout.setHorizontalGroup(
            jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpdateQtyLayout.createSequentialGroup()
                .addGroup(jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUpdateQtyLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel13))
                    .addGroup(jPanelUpdateQtyLayout.createSequentialGroup()
                        .addGroup(jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUpdateQtyLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabelUpdateQtyStatus))
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpdateQtyLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonUpdateQtyLoad)
                                    .addComponent(jLabelQty))
                                .addGap(32, 32, 32)))
                        .addGroup(jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelUpdateQtyLayout.createSequentialGroup()
                                .addComponent(jButtonUpdateQtyUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(jButtonUpdateQtyBack))
                            .addComponent(jTextFieldUpdateQtyName)
                            .addComponent(jTextFieldUpdateQtyNo)
                            .addComponent(jTextFieldUpdateQtyQty))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanelUpdateQtyLayout.setVerticalGroup(
            jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpdateQtyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUpdateQtyStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldUpdateQtyNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldUpdateQtyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldUpdateQtyQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdateQtyLoad)
                    .addComponent(jButtonUpdateQtyUpdate)
                    .addComponent(jButtonUpdateQtyBack))
                .addGap(24, 24, 24)
                .addComponent(jLabelQty)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrameUpdateQtyLayout = new javax.swing.GroupLayout(jFrameUpdateQty.getContentPane());
        jFrameUpdateQty.getContentPane().setLayout(jFrameUpdateQtyLayout);
        jFrameUpdateQtyLayout.setHorizontalGroup(
            jFrameUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelUpdateQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrameUpdateQtyLayout.setVerticalGroup(
            jFrameUpdateQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelUpdateQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFrameDeletePart.setMinimumSize(new java.awt.Dimension(550, 350));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Delete part");

        jLabel19.setText("Part No");

        jLabel20.setText("Part Name");

        jLabel21.setText("Part Quantity");

        jLabel22.setText("Part Description");

        jTextFieldDeletePartNo.setToolTipText("Leave empty for auto-number");
        jTextFieldDeletePartNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDeletePartNoFocusGained(evt);
            }
        });

        jButtonDeletePartDelete.setText("Delete Part");
        jButtonDeletePartDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletePartDeleteActionPerformed(evt);
            }
        });

        jButtonDeletePartBack.setText("Back");
        jButtonDeletePartBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletePartBackActionPerformed(evt);
            }
        });

        jButtonDeleteLoad.setText("Load");
        jButtonDeleteLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDeletePartLayout = new javax.swing.GroupLayout(jPanelDeletePart);
        jPanelDeletePart.setLayout(jPanelDeletePartLayout);
        jPanelDeletePartLayout.setHorizontalGroup(
            jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeletePartLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDeleteStatus)
                    .addGroup(jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelDeletePartLayout.createSequentialGroup()
                            .addComponent(jButtonDeleteLoad)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonDeletePartDelete)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                            .addComponent(jButtonDeletePartBack))
                        .addGroup(jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDeleted)
                            .addComponent(jLabel18)
                            .addGroup(jPanelDeletePartLayout.createSequentialGroup()
                                .addGroup(jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22))
                                .addGap(21, 21, 21)
                                .addGroup(jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldDeletePartName)
                                    .addComponent(jTextFieldDeletePartNo, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDeletePartQuantity)
                                    .addComponent(jTextFieldDeletePartDescription))))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanelDeletePartLayout.setVerticalGroup(
            jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeletePartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(9, 9, 9)
                .addComponent(jLabelDeleteStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldDeletePartNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldDeletePartName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextFieldDeletePartQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldDeletePartDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDeletePartDelete)
                    .addComponent(jButtonDeletePartBack)
                    .addComponent(jButtonDeleteLoad))
                .addGap(18, 18, 18)
                .addComponent(jLabelDeleted)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrameDeletePartLayout = new javax.swing.GroupLayout(jFrameDeletePart.getContentPane());
        jFrameDeletePart.getContentPane().setLayout(jFrameDeletePartLayout);
        jFrameDeletePartLayout.setHorizontalGroup(
            jFrameDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDeletePart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrameDeletePartLayout.setVerticalGroup(
            jFrameDeletePartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDeletePart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jTable1);

        jButtonAllPartsLoad.setText("Load Part");

        jButtonAllPartsBack.setText("Back");

        javax.swing.GroupLayout jPanelAllPartsLayout = new javax.swing.GroupLayout(jPanelAllParts);
        jPanelAllParts.setLayout(jPanelAllPartsLayout);
        jPanelAllPartsLayout.setHorizontalGroup(
            jPanelAllPartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAllPartsLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelAllPartsLayout.createSequentialGroup()
                .addComponent(jButtonAllPartsLoad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAllPartsBack)
                .addContainerGap())
        );
        jPanelAllPartsLayout.setVerticalGroup(
            jPanelAllPartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAllPartsLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanelAllPartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAllPartsLoad)
                    .addComponent(jButtonAllPartsBack))
                .addContainerGap())
        );

        javax.swing.GroupLayout jFrameAllPartsLayout = new javax.swing.GroupLayout(jFrameAllParts.getContentPane());
        jFrameAllParts.getContentPane().setLayout(jFrameAllPartsLayout);
        jFrameAllPartsLayout.setHorizontalGroup(
            jFrameAllPartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jFrameAllPartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrameAllPartsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelAllParts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jFrameAllPartsLayout.setVerticalGroup(
            jFrameAllPartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jFrameAllPartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrameAllPartsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelAllParts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Create new truck");

        jLabel26.setText("Truck No");

        jLabel31.setText("Truck Type");

        jLabel32.setText("Truck Status");

        jLabel33.setText("Order No");

        jTextFieldVognNewNo.setToolTipText("Leave empty for auto-number");
        jTextFieldVognNewNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldVognNewNoFocusGained(evt);
            }
        });

        jButtonSaveVogn.setText("Save Truck");
        jButtonSaveVogn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveVognActionPerformed(evt);
            }
        });

        jButtonNewVognBack.setText("Back");
        jButtonNewVognBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewVognBackActionPerformed(evt);
            }
        });

        jLabel34.setText("Reserved From");

        jLabel35.setText("Reserved Until");

        javax.swing.GroupLayout jPanelNewPart1Layout = new javax.swing.GroupLayout(jPanelNewPart1);
        jPanelNewPart1.setLayout(jPanelNewPart1Layout);
        jPanelNewPart1Layout.setHorizontalGroup(
            jPanelNewPart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewPart1Layout.createSequentialGroup()
                .addGroup(jPanelNewPart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNewPart1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanelNewPart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel34)
                            .addComponent(jLabel33)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31)
                            .addComponent(jLabel26))
                        .addGap(10, 10, 10)
                        .addGroup(jPanelNewPart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldVognNewResUntil)
                            .addComponent(jTextFieldVognNewResFrom)
                            .addComponent(jTextFieldVognNewType, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldVognNewNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(jTextFieldVognNewStatus, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldVognNewOno, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanelNewPart1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanelNewPart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNewPart1Layout.createSequentialGroup()
                                .addComponent(jButtonSaveVogn)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonNewVognBack))
                            .addComponent(jLabelSaved1)
                            .addComponent(jLabel25))))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jPanelNewPart1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel26, jLabel31, jLabel32, jLabel33, jLabel34, jLabel35});

        jPanelNewPart1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldVognNewNo, jTextFieldVognNewOno, jTextFieldVognNewResFrom, jTextFieldVognNewResUntil, jTextFieldVognNewStatus, jTextFieldVognNewType});

        jPanelNewPart1Layout.setVerticalGroup(
            jPanelNewPart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewPart1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(34, 34, 34)
                .addGroup(jPanelNewPart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextFieldVognNewNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNewPart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jTextFieldVognNewType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNewPart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jTextFieldVognNewStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNewPart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jTextFieldVognNewOno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNewPart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVognNewResFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNewPart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVognNewResUntil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGap(36, 36, 36)
                .addComponent(jLabelSaved1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNewPart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaveVogn)
                    .addComponent(jButtonNewVognBack))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanelNewPart1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel26, jLabel31, jLabel32, jLabel33, jLabel34, jLabel35});

        jPanelNewPart1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldVognNewNo, jTextFieldVognNewOno, jTextFieldVognNewResFrom, jTextFieldVognNewResUntil, jTextFieldVognNewStatus, jTextFieldVognNewType});

        javax.swing.GroupLayout jFrameNewVognLayout = new javax.swing.GroupLayout(jFrameNewVogn.getContentPane());
        jFrameNewVogn.getContentPane().setLayout(jFrameNewVognLayout);
        jFrameNewVognLayout.setHorizontalGroup(
            jFrameNewVognLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNewPart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrameNewVognLayout.setVerticalGroup(
            jFrameNewVognLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNewPart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane.setMinimumSize(new java.awt.Dimension(550, 350));

        jLabel1.setText("Part No");

        jLabel2.setText("Part Name");

        jLabel3.setText("Quantity");

        jLabel4.setText("Part Description");

        jButtonGetPart.setText("Get Part");
        jButtonGetPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetPartActionPerformed(evt);
            }
        });

        jButtonNewPart.setText("New Part");
        jButtonNewPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewPartActionPerformed(evt);
            }
        });

        jButtonUpdatePart.setText("Update Part");
        jButtonUpdatePart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdatePartActionPerformed(evt);
            }
        });

        jButtonUpdateQty.setText("Update Qty");
        jButtonUpdateQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateQtyActionPerformed(evt);
            }
        });

        jButtonDeletePart.setText("Delete Part");
        jButtonDeletePart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletePartActionPerformed(evt);
            }
        });

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonAllParts.setText("All Parts");
        jButtonAllParts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAllPartsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGetPartLayout = new javax.swing.GroupLayout(jPanelGetPart);
        jPanelGetPart.setLayout(jPanelGetPartLayout);
        jPanelGetPartLayout.setHorizontalGroup(
            jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGetPartLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGetPartLayout.createSequentialGroup()
                        .addGroup(jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelGetPartLayout.createSequentialGroup()
                                .addGroup(jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(28, 28, 28)
                                .addGroup(jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldPartNo)
                                    .addComponent(jTextFieldPartName)
                                    .addComponent(jTextFieldPartQuantity)
                                    .addComponent(jTextFieldPartDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                            .addGroup(jPanelGetPartLayout.createSequentialGroup()
                                .addComponent(jButtonGetPart, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonClear)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonUpdatePart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonNewPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonUpdateQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDeletePart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAllParts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanelGetPartLayout.setVerticalGroup(
            jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGetPartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPartNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAllParts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPartName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewPart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPartQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdatePart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldPartDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdateQty))
                .addGap(18, 18, 18)
                .addGroup(jPanelGetPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGetPart)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonDeletePart))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Parts", jPanelGetPart);

        jLabel27.setText("Truck No");

        jLabel28.setText("Truck Type");

        jLabel29.setText("Status");

        jLabel30.setText("Order No");

        jButtonGetVogn.setText("Get Truck");
        jButtonGetVogn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetVognActionPerformed(evt);
            }
        });

        jButtonNewVogn.setText("New Truck");
        jButtonNewVogn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewVognActionPerformed(evt);
            }
        });

        jButtonUpdateVogn.setText("Update Truck");
        jButtonUpdateVogn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateVognActionPerformed(evt);
            }
        });

        jButtonDeleteVogn.setText("Delete Truck");
        jButtonDeleteVogn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteVognActionPerformed(evt);
            }
        });

        jButtonVognClear.setText("Clear");
        jButtonVognClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVognClearActionPerformed(evt);
            }
        });

        jButtonAllVogn.setText("All Trucks");
        jButtonAllVogn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAllVognActionPerformed(evt);
            }
        });

        jLabel23.setText("Reserved From");

        jLabel24.setText("Reserved Until");

        javax.swing.GroupLayout jPanelGetVognLayout = new javax.swing.GroupLayout(jPanelGetVogn);
        jPanelGetVogn.setLayout(jPanelGetVognLayout);
        jPanelGetVognLayout.setHorizontalGroup(
            jPanelGetVognLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGetVognLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanelGetVognLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVognStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelGetVognLayout.createSequentialGroup()
                        .addComponent(jButtonGetVogn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonVognClear))
                    .addGroup(jPanelGetVognLayout.createSequentialGroup()
                        .addGroup(jPanelGetVognLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27))
                        .addGap(28, 28, 28)
                        .addGroup(jPanelGetVognLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldVognReservedFrom)
                            .addComponent(jTextFieldVognNo)
                            .addComponent(jTextFieldVognType)
                            .addComponent(jTextFieldVognStatus)
                            .addComponent(jTextFieldVognOno)
                            .addComponent(jTextFieldVognReservedTo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanelGetVognLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonUpdateVogn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonNewVogn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDeleteVogn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAllVogn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(87, 107, Short.MAX_VALUE))
        );

        jPanelGetVognLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldVognNo, jTextFieldVognOno, jTextFieldVognReservedFrom, jTextFieldVognReservedTo, jTextFieldVognStatus, jTextFieldVognType});

        jPanelGetVognLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel23, jLabel24, jLabel27, jLabel28, jLabel29, jLabel30});

        jPanelGetVognLayout.setVerticalGroup(
            jPanelGetVognLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGetVognLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVognStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelGetVognLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextFieldVognNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAllVogn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGetVognLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextFieldVognType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewVogn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGetVognLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTextFieldVognStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdateVogn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGetVognLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jTextFieldVognOno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteVogn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGetVognLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVognReservedFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGetVognLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVognReservedTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanelGetVognLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGetVogn)
                    .addComponent(jButtonVognClear))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanelGetVognLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldVognNo, jTextFieldVognOno, jTextFieldVognReservedFrom, jTextFieldVognReservedTo, jTextFieldVognStatus, jTextFieldVognType});

        jTabbedPane.addTab("Fleet", jPanelGetVogn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGetPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetPartActionPerformed
        // TODO add your handling code here:
        int pnum = 0;

        if (jTextFieldPartNo.getText().equals("")) {
            pnum = 0;
        } else {
            pnum = Integer.parseInt(jTextFieldPartNo.getText());
        }

        clearGetFields();
        Part p = pc.getPart(pnum);

        if (p != null) {
            jTextFieldPartName.setText(p.getPnavn());
            jTextFieldPartNo.setText(p.getPnum() + "");
            jTextFieldPartQuantity.setText(p.getQty() + "");
            jTextFieldPartDescription.setText(p.getPbeskrivelse());
        } else {
            jLabelStatus.setText("No such part!");
        }

    }//GEN-LAST:event_jButtonGetPartActionPerformed

    private void jButtonNewPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewPartActionPerformed
        // TODO add your handling code here:
        jFrameNewPart.setVisible(true);
    }//GEN-LAST:event_jButtonNewPartActionPerformed

    private void jButtonSavePartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSavePartActionPerformed
        // TODO add your handling code here:
        String newName = jTextFieldNewPartName.getText();
        int newQty = Integer.parseInt(jTextFieldNewPartQuantity.getText());
        String newDesc = jTextFieldNewPartDescription.getText();

        if (jTextFieldNewPartNo.getText().compareTo("") == 0) {
            try {
                Part p = new Part(newName, newDesc, newQty);
                pc.saveNewPart(p);
                clearNewFields();
                jLabelSaved.setText("Saved");
            } catch (NumberFormatException | SQLException ex) {
                ex.
                if (ex.getErrorCode() == 1) {
                    JOptionPane.showMessageDialog(null, "The Part No is already in use, please use another", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            try {
                Part p = new Part(Integer.parseInt(jTextFieldNewPartNo.getText()), newName, newDesc, newQty);
                pc.saveNewPartWitnum(p);
                clearNewFields();
                jLabelSaved.setText("Saved");
            } catch (NumberFormatException | SQLException ex) {
                if (ex.getErrorCode() == 1) {
                    JOptionPane.showMessageDialog(null, "The Part No is already in use, please use another", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButtonSavePartActionPerformed

    private void jButtonNewPartBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewPartBackActionPerformed
        // TODO add your handling code here:
        jFrameNewPart.setVisible(false);
        jFrameNewPart.dispose();
        clearNewFields();
    }//GEN-LAST:event_jButtonNewPartBackActionPerformed

    private void jButtonUpdatePartUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdatePartUpdateActionPerformed
        // TODO add your handling code here:
        String updateName = jTextFieldUpdatePartName.getText();
        String updateDescription = jTextFieldUpdatePartDescription.getText();
        int updatePnum = Integer.parseInt(jTextFieldUpdatePartNo.getText());

        Part p = new Part(updatePnum, updateName, updateDescription, 0);

        pc.updatePart(p);

        clearUpdateFields();
        jLabelUpdated.setText("Updated");
    }//GEN-LAST:event_jButtonUpdatePartUpdateActionPerformed

    private void jButtonUpdatePartBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdatePartBackActionPerformed
        // TODO add your handling code here:
        jFrameUpdatePart.setVisible(false);
        jFrameUpdatePart.dispose();
        clearUpdateFields();
    }//GEN-LAST:event_jButtonUpdatePartBackActionPerformed

    private void jButtonUpdatePartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdatePartActionPerformed
        // TODO add your handling code here:
        jFrameUpdatePart.setVisible(true);
    }//GEN-LAST:event_jButtonUpdatePartActionPerformed

    private void jButtonUpdatePartLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdatePartLoadActionPerformed
        // TODO add your handling code here:
        int pnum = 0;

        if (jTextFieldUpdatePartNo.getText().equals("")) {
            pnum = 0;
        } else {
            pnum = Integer.parseInt(jTextFieldUpdatePartNo.getText());
        }

        Part p = pc.getPart(pnum);

        if (p != null) {
            jTextFieldUpdatePartName.setText(p.getPnavn());
            jTextFieldUpdatePartNo.setText(p.getPnum() + "");
            jTextFieldUpdatePartDescription.setText(p.getPbeskrivelse());
        } else {
            jLabelUpdateStatus.setText("No such part!");
        }
    }//GEN-LAST:event_jButtonUpdatePartLoadActionPerformed

    private void jButtonUpdateQtyUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateQtyUpdateActionPerformed
        // TODO add your handling code here:
        int pnum, qty;

        if (jTextFieldUpdateQtyNo.getText().equals("")) {
            pnum = 0;
        } else {
            pnum = Integer.parseInt(jTextFieldUpdateQtyNo.getText());
        }

        if (jTextFieldUpdateQtyQty.getText().equals("")) {
            qty = 0;
        } else {
            qty = Integer.parseInt(jTextFieldUpdateQtyQty.getText());
        }

        pc.updatePartQty(pnum, qty);

        clearUpdateQtyFields();
        jLabelQty.setText("Updated");
    }//GEN-LAST:event_jButtonUpdateQtyUpdateActionPerformed

    private void jButtonUpdateQtyBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateQtyBackActionPerformed
        // TODO add your handling code here:
        jFrameUpdateQty.setVisible(false);
        jFrameUpdateQty.dispose();
        clearUpdateQtyFields();
    }//GEN-LAST:event_jButtonUpdateQtyBackActionPerformed

    private void jButtonUpdateQtyLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateQtyLoadActionPerformed
        // TODO add your handling code here:
        int pnum = 0;

        if (jTextFieldUpdateQtyNo.getText().equals("")) {
            pnum = 0;
        } else {
            pnum = Integer.parseInt(jTextFieldUpdateQtyNo.getText());
        }

        clearDeleteFields();

        Part p = pc.getPart(pnum);

        if (p != null) {
            jTextFieldUpdateQtyName.setText(p.getPnavn());
            jTextFieldUpdateQtyNo.setText(p.getPnum() + "");
            jTextFieldUpdateQtyQty.setText(p.getQty() + "");
        } else {
            jLabelUpdateQtyStatus.setText("No such part!");
        }
    }//GEN-LAST:event_jButtonUpdateQtyLoadActionPerformed

    private void jButtonUpdateQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateQtyActionPerformed
        // TODO add your handling code here:
        jFrameUpdateQty.setVisible(true);
    }//GEN-LAST:event_jButtonUpdateQtyActionPerformed

    private void jButtonDeletePartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletePartActionPerformed
        // TODO add your handling code here:
        jFrameDeletePart.setVisible(true);
    }//GEN-LAST:event_jButtonDeletePartActionPerformed

    private void jButtonDeletePartDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletePartDeleteActionPerformed
        // TODO add your handling code here:
        int pnum;

        if (jTextFieldDeletePartNo.getText().equals("")) {
            pnum = 0;
        } else {
            pnum = Integer.parseInt(jTextFieldDeletePartNo.getText());
        }

        int reply = JOptionPane.showConfirmDialog(null, "Deleting cannot be undone. Are you sure you want to delete this part?",
                "Warning", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            pc.deletePart(pnum);
        }

        clearDeleteFields2();
        jLabelDeleted.setText("Deleted");
    }//GEN-LAST:event_jButtonDeletePartDeleteActionPerformed

    private void jButtonDeletePartBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletePartBackActionPerformed
        // TODO add your handling code here:
        jFrameDeletePart.setVisible(false);
        jFrameDeletePart.dispose();
        clearDeleteFields();
    }//GEN-LAST:event_jButtonDeletePartBackActionPerformed

    private void jButtonDeleteLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteLoadActionPerformed
        // TODO add your handling code here:
        int pnum = 0;

        if (jTextFieldDeletePartNo.getText().equals("")) {
            pnum = 0;
        } else {
            pnum = Integer.parseInt(jTextFieldDeletePartNo.getText());
        }

        clearUpdateQtyFields();

        Part p = pc.getPart(pnum);

        if (p != null) {
            jTextFieldDeletePartName.setText(p.getPnavn());
            jTextFieldDeletePartNo.setText(p.getPnum() + "");
            jTextFieldDeletePartQuantity.setText(p.getQty() + "");
            jTextFieldDeletePartDescription.setText(p.getPbeskrivelse());
        } else {
            jLabelDeleteStatus.setText("No such part!");
        }
    }//GEN-LAST:event_jButtonDeleteLoadActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        clearGetFields();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jTextFieldNewPartNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNewPartNoFocusGained
        // TODO add your handling code here:
        jLabelSaved.setText("");
    }//GEN-LAST:event_jTextFieldNewPartNoFocusGained

    private void jTextFieldUpdatePartNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUpdatePartNoFocusGained
        // TODO add your handling code here:
        jLabelUpdated.setText("");
        jLabelUpdateStatus.setText("");
    }//GEN-LAST:event_jTextFieldUpdatePartNoFocusGained

    private void jTextFieldUpdateQtyNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUpdateQtyNoFocusGained
        // TODO add your handling code here:
        jLabelUpdateQtyStatus.setText("");
        jLabelQty.setText("");
    }//GEN-LAST:event_jTextFieldUpdateQtyNoFocusGained

    private void jTextFieldDeletePartNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDeletePartNoFocusGained
        // TODO add your handling code here:
        jLabelDeleteStatus.setText("");
        jLabelDeleted.setText("");
    }//GEN-LAST:event_jTextFieldDeletePartNoFocusGained

    private void jButtonAllPartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAllPartsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonAllPartsActionPerformed

    private void jButtonGetVognActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetVognActionPerformed
        // TODO add your handling code here:
        int vognID = 0;

        if (jTextFieldVognNo.getText().equals("")) {
            vognID = 0;
        } else {
            vognID = Integer.parseInt(jTextFieldVognNo.getText());
        }

        clearVognFields();

        Vogn v = vc.getVogn(vognID);

        if (v != null) {
            jTextFieldVognNo.setText(v.getVognID() + "");
            jTextFieldVognOno.setText(v.getOno() + "");
            jTextFieldVognType.setText(v.getvType());
            jTextFieldVognStatus.setText(v.getStatus());
            jTextFieldVognReservedFrom.setText(v.getReserveretFra());
            jTextFieldVognReservedTo.setText(v.getReserveretTil());
        } else {
            jLabelVognStatus.setText("No such truck");
        }
    }//GEN-LAST:event_jButtonGetVognActionPerformed

    private void jButtonNewVognActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewVognActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNewVognActionPerformed

    private void jButtonUpdateVognActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateVognActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpdateVognActionPerformed

    private void jButtonDeleteVognActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteVognActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteVognActionPerformed

    private void jButtonVognClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVognClearActionPerformed
        // TODO add your handling code here:
        clearVognFields();
    }//GEN-LAST:event_jButtonVognClearActionPerformed

    private void jButtonAllVognActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAllVognActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAllVognActionPerformed

    private void jTextFieldVognNewNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldVognNewNoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVognNewNoFocusGained

    private void jButtonSaveVognActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveVognActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonSaveVognActionPerformed

    private void jButtonNewVognBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewVognBackActionPerformed
        // TODO add your handling code here:
        jFrameNewVogn.setVisible(false);
        jFrameNewVogn.dispose();
        clearVognFields();
    }//GEN-LAST:event_jButtonNewVognBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResourceManagementSystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResourceManagementSystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResourceManagementSystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResourceManagementSystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResourceManagementSystemFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAllParts;
    private javax.swing.JButton jButtonAllPartsBack;
    private javax.swing.JButton jButtonAllPartsLoad;
    private javax.swing.JButton jButtonAllVogn;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDeleteLoad;
    private javax.swing.JButton jButtonDeletePart;
    private javax.swing.JButton jButtonDeletePartBack;
    private javax.swing.JButton jButtonDeletePartDelete;
    private javax.swing.JButton jButtonDeleteVogn;
    private javax.swing.JButton jButtonGetPart;
    private javax.swing.JButton jButtonGetVogn;
    private javax.swing.JButton jButtonNewPart;
    private javax.swing.JButton jButtonNewPartBack;
    private javax.swing.JButton jButtonNewVogn;
    private javax.swing.JButton jButtonNewVognBack;
    private javax.swing.JButton jButtonSavePart;
    private javax.swing.JButton jButtonSaveVogn;
    private javax.swing.JButton jButtonUpdatePart;
    private javax.swing.JButton jButtonUpdatePartBack;
    private javax.swing.JButton jButtonUpdatePartLoad;
    private javax.swing.JButton jButtonUpdatePartUpdate;
    private javax.swing.JButton jButtonUpdateQty;
    private javax.swing.JButton jButtonUpdateQtyBack;
    private javax.swing.JButton jButtonUpdateQtyLoad;
    private javax.swing.JButton jButtonUpdateQtyUpdate;
    private javax.swing.JButton jButtonUpdateVogn;
    private javax.swing.JButton jButtonVognClear;
    private javax.swing.JFrame jFrameAllParts;
    private javax.swing.JFrame jFrameDeletePart;
    private javax.swing.JFrame jFrameNewPart;
    private javax.swing.JFrame jFrameNewVogn;
    private javax.swing.JFrame jFrameUpdatePart;
    private javax.swing.JFrame jFrameUpdateQty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDeleteStatus;
    private javax.swing.JLabel jLabelDeleted;
    private javax.swing.JLabel jLabelQty;
    private javax.swing.JLabel jLabelSaved;
    private javax.swing.JLabel jLabelSaved1;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelUpdateQtyStatus;
    private javax.swing.JLabel jLabelUpdateStatus;
    private javax.swing.JLabel jLabelUpdated;
    private javax.swing.JLabel jLabelVognStatus;
    private javax.swing.JPanel jPanelAllParts;
    private javax.swing.JPanel jPanelDeletePart;
    private javax.swing.JPanel jPanelGetPart;
    private javax.swing.JPanel jPanelGetVogn;
    private javax.swing.JPanel jPanelNewPart;
    private javax.swing.JPanel jPanelNewPart1;
    private javax.swing.JPanel jPanelUpdatePart;
    private javax.swing.JPanel jPanelUpdateQty;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDeletePartDescription;
    private javax.swing.JTextField jTextFieldDeletePartName;
    private javax.swing.JTextField jTextFieldDeletePartNo;
    private javax.swing.JTextField jTextFieldDeletePartQuantity;
    private javax.swing.JTextField jTextFieldNewPartDescription;
    private javax.swing.JTextField jTextFieldNewPartName;
    private javax.swing.JTextField jTextFieldNewPartNo;
    private javax.swing.JTextField jTextFieldNewPartQuantity;
    private javax.swing.JTextField jTextFieldPartDescription;
    private javax.swing.JTextField jTextFieldPartName;
    private javax.swing.JTextField jTextFieldPartNo;
    private javax.swing.JTextField jTextFieldPartQuantity;
    private javax.swing.JTextField jTextFieldUpdatePartDescription;
    private javax.swing.JTextField jTextFieldUpdatePartName;
    private javax.swing.JTextField jTextFieldUpdatePartNo;
    private javax.swing.JTextField jTextFieldUpdateQtyName;
    private javax.swing.JTextField jTextFieldUpdateQtyNo;
    private javax.swing.JTextField jTextFieldUpdateQtyQty;
    private javax.swing.JTextField jTextFieldVognNewNo;
    private javax.swing.JTextField jTextFieldVognNewOno;
    private javax.swing.JTextField jTextFieldVognNewResFrom;
    private javax.swing.JTextField jTextFieldVognNewResUntil;
    private javax.swing.JTextField jTextFieldVognNewStatus;
    private javax.swing.JTextField jTextFieldVognNewType;
    private javax.swing.JTextField jTextFieldVognNo;
    private javax.swing.JTextField jTextFieldVognOno;
    private javax.swing.JTextField jTextFieldVognReservedFrom;
    private javax.swing.JTextField jTextFieldVognReservedTo;
    private javax.swing.JTextField jTextFieldVognStatus;
    private javax.swing.JTextField jTextFieldVognType;
    // End of variables declaration//GEN-END:variables
}
